### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [kuangyujing/dracula-xfce4-terminal#5]
Hey @kuangyujing 👋 

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by kuangyujing** [comment]
@zenorocha

Thank you for contact me. Off cause, I'm pleased to join official org.🧛🏻‍♂️

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by kiraitachi** [comment]
Good job @zenorocha  for pointing this out. I was searching in Dracula website for a XFCE4 dracula theme and couldn't find it. Thankfully I ended up searching on Github where always someone has some half backed project. 

I would strongly suggest @kuangyujing  to move it to the official org as soon as possible. More visibility to the project will be added . :blush:

**Comment by kuangyujing** [comment]
@kiraitachi
I just transfered this project to @dracula/xcfe4.

**Comment by zenorocha** [comment]
https://draculatheme.com/xfce4-terminal 💥 💥 💥

**Comment by kuangyujing** [comment]
> [draculatheme.com/xfce4-terminal](https://draculatheme.com/xfce4-terminal)

Great! Thanks @zenorocha 🧛‍♂️
