### ISSUE TITLE
not following template layout

### ISSUE THREAD

**Issue by davison** [kuangyujing/dracula-xfce4-terminal#6]
I created an xfce4 terminal theme myself and was about to add it when I came across this one. This doesn't show up on the main search page at https://draculatheme.com/ - probably because it's not following the template repo layout https://github.com/dracula/template.

Think the name of this repo should also not include the `dracula-` prefix, but not sure if that's the thing that stops it showing up.

I can create a branch/PR in here for those suggestions if you want to add me as a contributor (my own version of this is a local only repo right now)

**Comment by kuangyujing** [comment]
Thanks @davison!
I'll check and fix this as soon as possible. And PR is welcome!

**Comment by davison** [comment]
sure.. are you happy to add me as a contributor to this repo? It will save me forking/cloning. I can create a branch, push the changes I have from local direct to here and create a local PR. (I'm the author of https://github.com/dracula/midnight-commander if that helps) . If not, I'll fork/clone

**Comment by kuangyujing** [comment]
@davison 
Thank you!👍 I added you as a member.

**Comment by zenorocha** [comment]
Thank you so much @davison. I some other changes to be 100% standardized with the rest :)

https://github.com/dracula/xfce4-terminal/commit/492e25caf38ddafc8a51176a8dd11e826302faac
